// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by  version  DO NOT EDIT.
package interfaces

const (
	Jwt_header_AuthorizationScopes = "jwt_header_Authorization.Scopes"
)

// Defines values for CreateRequestBodyPrepayTariff.
const (
	CreateRequestBodyPrepayTariffFalse CreateRequestBodyPrepayTariff = false

	CreateRequestBodyPrepayTariffTrue CreateRequestBodyPrepayTariff = true
)

// Defines values for CreateRequestBodyTest.
const (
	CreateRequestBodyTestFalse CreateRequestBodyTest = false

	CreateRequestBodyTestTrue CreateRequestBodyTest = true
)

// Defines values for CreateRequestBodyType.
const (
	CreateRequestBodyTypeN1 CreateRequestBodyType = 1

	CreateRequestBodyTypeN2 CreateRequestBodyType = 2

	CreateRequestBodyTypeN3 CreateRequestBodyType = 3
)

// Defines values for GetChannelInfoHasChannelCost.
const (
	GetChannelInfoHasChannelCostFalse GetChannelInfoHasChannelCost = false

	GetChannelInfoHasChannelCostTrue GetChannelInfoHasChannelCost = true
)

// Defines values for GetChannelInfoPrepayTariff.
const (
	GetChannelInfoPrepayTariffFalse GetChannelInfoPrepayTariff = false

	GetChannelInfoPrepayTariffTrue GetChannelInfoPrepayTariff = true
)

// Defines values for GetChannelInfoTest.
const (
	GetChannelInfoTestFalse GetChannelInfoTest = false

	GetChannelInfoTestTrue GetChannelInfoTest = true
)

// Defines values for GetChannelInfoType.
const (
	GetChannelInfoTypeN1 GetChannelInfoType = 1

	GetChannelInfoTypeN2 GetChannelInfoType = 2

	GetChannelInfoTypeN3 GetChannelInfoType = 3
)

// Defines values for QueryCustomerConfigDataStatus.
const (
	QueryCustomerConfigDataStatusFalse QueryCustomerConfigDataStatus = false

	QueryCustomerConfigDataStatusTrue QueryCustomerConfigDataStatus = true
)

// Defines values for QueryRecommendDataIsRecommended.
const (
	QueryRecommendDataIsRecommendedFalse QueryRecommendDataIsRecommended = false

	QueryRecommendDataIsRecommendedTrue QueryRecommendDataIsRecommended = true
)

// Defines values for QueryRecommendDataStatus.
const (
	QueryRecommendDataStatusFalse QueryRecommendDataStatus = false

	QueryRecommendDataStatusTrue QueryRecommendDataStatus = true
)

// Defines values for UpdateChannelCostStatusRequestBodyStatus.
const (
	UpdateChannelCostStatusRequestBodyStatusFalse UpdateChannelCostStatusRequestBodyStatus = false

	UpdateChannelCostStatusRequestBodyStatusTrue UpdateChannelCostStatusRequestBodyStatus = true
)

// Defines values for UpdateCustomerConfigRequestBodyStatus.
const (
	UpdateCustomerConfigRequestBodyStatusFalse UpdateCustomerConfigRequestBodyStatus = false

	UpdateCustomerConfigRequestBodyStatusTrue UpdateCustomerConfigRequestBodyStatus = true
)

// Defines values for UpdateRecommendRequestBodyIsRecommended.
const (
	UpdateRecommendRequestBodyIsRecommendedFalse UpdateRecommendRequestBodyIsRecommended = false

	UpdateRecommendRequestBodyIsRecommendedTrue UpdateRecommendRequestBodyIsRecommended = true
)

// Defines values for UpdateRecommendRequestBodyStatus.
const (
	UpdateRecommendRequestBodyStatusFalse UpdateRecommendRequestBodyStatus = false

	UpdateRecommendRequestBodyStatusTrue UpdateRecommendRequestBodyStatus = true
)

// Defines values for UpdateRequestBodyPrepayTariff.
const (
	UpdateRequestBodyPrepayTariffFalse UpdateRequestBodyPrepayTariff = false

	UpdateRequestBodyPrepayTariffTrue UpdateRequestBodyPrepayTariff = true
)

// Defines values for UpdateRequestBodyTest.
const (
	UpdateRequestBodyTestFalse UpdateRequestBodyTest = false

	UpdateRequestBodyTestTrue UpdateRequestBodyTest = true
)

// Defines values for UpdateRequestBodyType.
const (
	UpdateRequestBodyTypeN1 UpdateRequestBodyType = 1

	UpdateRequestBodyTypeN2 UpdateRequestBodyType = 2

	UpdateRequestBodyTypeN3 UpdateRequestBodyType = 3
)

// BatchUpdateRequestBody defines model for BatchUpdateRequestBody.
type BatchUpdateRequestBody struct {
	// 渠道属性
	Attribute *string `json:"attribute,omitempty"`

	// 渠道ID
	ChannelIds *[]int64 `json:"channel_ids,omitempty"`
}

// ChannelCostBatchInfo defines model for ChannelCostBatchInfo.
type ChannelCostBatchInfo struct {
	// 渠道ID
	ChannelId int64 `json:"channel_id"`

	// 生效日期
	EffectiveDate string `json:"effective_date"`

	// 渠道批次ID
	Id int64 `json:"id"`

	// 状态
	Status int `json:"status"`

	// 更新时间
	UpdatedAt string `json:"updated_at"`
}

// ChannelCostBatchSearchInfo defines model for ChannelCostBatchSearchInfo.
type ChannelCostBatchSearchInfo struct {
	// 具体渠道批次信息
	List []ChannelCostBatchInfo `json:"list"`

	// MetaData describes the MetaData
	Meta MetaData `json:"meta"`
}

// ChannelCostBatchSearchRsp defines model for ChannelCostBatchSearchRsp.
type ChannelCostBatchSearchRsp struct {
	// code
	Code int64                       `json:"code"`
	Data *ChannelCostBatchSearchInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// ChannelCostInfo defines model for ChannelCostInfo.
type ChannelCostInfo struct {
	// 平均派达天数
	AverageDays int `json:"average_days"`

	// 渠道代码
	ChannelCode string `json:"channel_code"`

	// 渠道批次ID
	ChannelCostBatchId int64 `json:"channel_cost_batch_id"`

	// 渠道ID
	ChannelId int64 `json:"channel_id"`

	// 国家代码
	CountryCode string `json:"country_code"`

	// 结束重量
	EndWeight int `json:"end_weight"`

	// 首重
	FirstWeight int `json:"first_weight"`

	// 首重费用
	FirstWeightFee float64 `json:"first_weight_fee"`

	// 燃油费
	FuelFee float64 `json:"fuel_fee"`

	// 渠道报价ID
	Id int64 `json:"id"`

	// 最大派达天数
	MaxNormalDays int `json:"max_normal_days"`

	// 最小派达天数
	MinNormalDays int `json:"min_normal_days"`

	// 渠道杂费
	MiscFee float64 `json:"misc_fee"`

	// 计费模式
	Mode int8 `json:"mode"`

	// 渠道操作费
	ProcessingFee float64 `json:"processing_fee"`

	// 渠道挂号费
	RegistrationFee float64 `json:"registration_fee"`

	// 起始重量
	StartWeight int `json:"start_weight"`

	// 状态
	Status int8 `json:"status"`

	// 计费单位
	UnitWeight *int `json:"unit_weight,omitempty"`

	// 计费单位费用
	UnitWeightFee *float64 `json:"unit_weight_fee,omitempty"`

	// 区域
	Zone string `json:"zone"`
}

// ChannelCostSearchInfo defines model for ChannelCostSearchInfo.
type ChannelCostSearchInfo struct {
	// 具体渠道批次信息
	List []ChannelCostInfo `json:"list"`

	// MetaData describes the MetaData
	Meta MetaData `json:"meta"`
}

// ChannelCostSearchRsp defines model for ChannelCostSearchRsp.
type ChannelCostSearchRsp struct {
	// code
	Code int64                  `json:"code"`
	Data *ChannelCostSearchInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// ChannelSearchInfo defines model for ChannelSearchInfo.
type ChannelSearchInfo struct {
	// 具体渠道信息
	List []GetChannelInfo `json:"list"`

	// MetaData describes the MetaData
	Meta MetaData `json:"meta"`
}

// ChannelSearchRsp defines model for ChannelSearchRsp.
type ChannelSearchRsp struct {
	// code
	Code int64              `json:"code"`
	Data *ChannelSearchInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateAttributeData defines model for CreateAttributeData.
type CreateAttributeData struct {
	// 状态（0 创建成功 1 创建失败）
	Status *int32 `json:"status,omitempty"`
}

// CreateAttributeRequestBody defines model for CreateAttributeRequestBody.
type CreateAttributeRequestBody struct {
	// 渠道属性
	Attribute *string `json:"attribute,omitempty"`
}

// CreateAttributeRsp defines model for CreateAttributeRsp.
type CreateAttributeRsp struct {
	// code
	Code int64                `json:"code"`
	Data *CreateAttributeData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateChannelCostBatchInfo defines model for CreateChannelCostBatchInfo.
type CreateChannelCostBatchInfo struct {
	// 渠道批次ID
	ChannelCostBatchId int64 `json:"channel_cost_batch_id"`
}

// CreateChannelCostBatchRequestBody defines model for CreateChannelCostBatchRequestBody.
type CreateChannelCostBatchRequestBody struct {
	// 生效日期
	EffectiveDate string `json:"effective_date"`

	// 状态
	Status int `json:"status"`
}

// CreateChannelCostBatchRsp defines model for CreateChannelCostBatchRsp.
type CreateChannelCostBatchRsp struct {
	// code
	Code int64                       `json:"code"`
	Data *CreateChannelCostBatchInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateChannelInfo defines model for CreateChannelInfo.
type CreateChannelInfo struct {
	// 渠道ID
	ChannelId int64 `json:"channel_id"`
}

// CreateChannelRsp defines model for CreateChannelRsp.
type CreateChannelRsp struct {
	// code
	Code int64              `json:"code"`
	Data *CreateChannelInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateCustomerConfigData defines model for CreateCustomerConfigData.
type CreateCustomerConfigData struct {
	// 状态（0 创建成功 1 创建失败）
	Status int32 `json:"status"`
}

// CreateCustomerConfigRequestBody defines model for CreateCustomerConfigRequestBody.
type CreateCustomerConfigRequestBody struct {
	// 排除国际二字码
	CountryCodes []string `json:"country_codes"`

	// 渠道ID
	Ids []int64 `json:"ids"`
}

// CreateCustomerConfigRsp defines model for CreateCustomerConfigRsp.
type CreateCustomerConfigRsp struct {
	// code
	Code int64                     `json:"code"`
	Data *CreateCustomerConfigData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateRecommendData defines model for CreateRecommendData.
type CreateRecommendData struct {
	// 状态（0 创建成功 1 创建失败）
	Status int32 `json:"status"`
}

// CreateRecommendRequestBody defines model for CreateRecommendRequestBody.
type CreateRecommendRequestBody struct {
	// 国际二字码
	CountryCode string `json:"country_code"`
}

// CreateRecommendRsp defines model for CreateRecommendRsp.
type CreateRecommendRsp struct {
	// code
	Code int64                `json:"code"`
	Data *CreateRecommendData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// CreateRequestBody defines model for CreateRequestBody.
type CreateRequestBody struct {
	// 渠道类型（1 快递, 2 专线， 3邮政）
	ChannelType int8 `json:"channel_type"`

	// API服务代码
	Code string `json:"code"`

	// 渠道平台
	CourierPlatform string `json:"courier_platform"`

	// 渠道类型（ddu, ddp）
	DeliverDuty string `json:"deliver_duty"`

	// 渠道对外展示名称
	DisplayName string `json:"display_name"`

	// 渠道英文名称
	EnName string `json:"en_name"`

	// 排除属性
	ExcludeAttributes []string `json:"exclude_attributes"`

	// 最大边长
	MaxLength *int `json:"max_length,omitempty"`

	// 最大三边之和(长+宽+高)
	MaxThreeSideSum *int `json:"max_three_side_sum,omitempty"`

	// 最小边长
	MinLength *int `json:"min_length,omitempty"`

	// 渠道中文名称
	Name string `json:"name"`

	// 是否启动预付关税
	PrepayTariff CreateRequestBodyPrepayTariff `json:"prepay_tariff"`

	// 流水线出口
	SortingPort int32 `json:"sorting_port"`

	// 是否特殊渠道（0 正常 1 特别）
	Special int8 `json:"special"`

	// 渠道可用状态
	Status int8 `json:"status"`

	// 是否是测试渠道
	Test CreateRequestBodyTest `json:"test"`

	// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
	Type CreateRequestBodyType `json:"type"`

	// 是否虚拟渠道（0 虚拟 1 真实）
	Virtual int8 `json:"virtual"`

	// 计泡系数
	VolumeFactor *int `json:"volume_factor,omitempty"`
}

// 是否启动预付关税
type CreateRequestBodyPrepayTariff bool

// 是否是测试渠道
type CreateRequestBodyTest bool

// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
type CreateRequestBodyType int

// Error defines model for Error.
type Error struct {
	// code (错误码).
	Code int `json:"code"`

	// message (错误信息).
	Message string `json:"message"`
}

// GetChannelInfo defines model for GetChannelInfo.
type GetChannelInfo struct {
	// 渠道类型（1 快递, 2 专线， 3邮政）
	ChannelType int8 `json:"channel_type"`

	// API服务代码
	Code string `json:"code"`

	// 渠道平台
	CourierPlatform string `json:"courier_platform"`

	// 目的国关税类型（ddu, ddp）
	DeliverDuty string `json:"deliver_duty"`

	// 渠道对外展示名称
	DisplayName string `json:"display_name"`

	// 渠道英文名称
	EnName string `json:"en_name"`

	// 是否有渠道报价信息
	HasChannelCost GetChannelInfoHasChannelCost `json:"has_channel_cost"`

	// 渠道ID
	Id int64 `json:"id"`

	// 最大边长
	MaxLength *int `json:"max_length,omitempty"`

	// 最大三边之和(长+宽+高)
	MaxThreeSideSum *int `json:"max_three_side_sum,omitempty"`

	// 最小边长
	MinLength *int `json:"min_length,omitempty"`

	// 渠道中文名称
	Name string `json:"name"`

	// 是否启动预付关税（增值税）
	PrepayTariff GetChannelInfoPrepayTariff `json:"prepay_tariff"`

	// 计费货币
	QuotationCurrency string `json:"quotation_currency"`

	// 流水线出口
	SortingPort int32 `json:"sorting_port"`

	// 是否特殊渠道（0 正常 1 特别）
	Special int8 `json:"special"`

	// 渠道可用状态
	Status int8 `json:"status"`

	// 是否是测试渠道
	Test GetChannelInfoTest `json:"test"`

	// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
	Type GetChannelInfoType `json:"type"`

	// 更新时间
	UpdatedAt string `json:"updated_at"`

	// 是否虚拟渠道（0 虚拟 1 真实）
	Virtual int8 `json:"virtual"`

	// 计泡系数
	VolumeFactor *int `json:"volume_factor,omitempty"`

	// 仓库ID
	WarehouseId int64 `json:"warehouse_id"`
}

// 是否有渠道报价信息
type GetChannelInfoHasChannelCost bool

// 是否启动预付关税（增值税）
type GetChannelInfoPrepayTariff bool

// 是否是测试渠道
type GetChannelInfoTest bool

// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
type GetChannelInfoType int

// MetaData describes the MetaData
type MetaData struct {
	// current
	Current int `json:"current"`

	// page_size
	PageSize int `json:"page_size"`

	// total
	Total int64 `json:"total"`
}

// QueryAttributeData defines model for QueryAttributeData.
type QueryAttributeData struct {
	// 渠道属性
	Attribute string `json:"attribute"`
}

// QueryAttributeInfo defines model for QueryAttributeInfo.
type QueryAttributeInfo struct {
	// 渠道属性数据
	List []QueryAttributeData `json:"list"`
}

// QueryAttributeRsp defines model for QueryAttributeRsp.
type QueryAttributeRsp struct {
	// code
	Code int64               `json:"code"`
	Data *QueryAttributeInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// QueryCustomerConfigData defines model for QueryCustomerConfigData.
type QueryCustomerConfigData struct {
	// 渠道ID
	ChannelId int64 `json:"channel_id"`

	// 排除国家二字码
	CountryCode []string `json:"country_code"`

	// 是否可用
	Status QueryCustomerConfigDataStatus `json:"status"`

	// 更新时间
	UpdatedAt string `json:"updated_at"`
}

// 是否可用
type QueryCustomerConfigDataStatus bool

// QueryCustomerConfigInfo defines model for QueryCustomerConfigInfo.
type QueryCustomerConfigInfo struct {
	// 用户自定义基于渠道排除国家数据
	List []QueryCustomerConfigData `json:"list"`

	// MetaData describes the MetaData
	Meta MetaData `json:"meta"`
}

// QueryCustomerConfigRsp defines model for QueryCustomerConfigRsp.
type QueryCustomerConfigRsp struct {
	// code
	Code int64                    `json:"code"`
	Data *QueryCustomerConfigInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// QueryRecommendData defines model for QueryRecommendData.
type QueryRecommendData struct {
	// 渠道ID
	ChannelId int64 `json:"channel_id"`

	// 国际二字码
	CountryCode string `json:"country_code"`

	// 是否推荐
	IsRecommended QueryRecommendDataIsRecommended `json:"is_recommended"`

	// 是否可用
	Status QueryRecommendDataStatus `json:"status"`

	// 更新时间
	UpdatedAt string `json:"updated_at"`
}

// 是否推荐
type QueryRecommendDataIsRecommended bool

// 是否可用
type QueryRecommendDataStatus bool

// QueryRecommendInfo defines model for QueryRecommendInfo.
type QueryRecommendInfo struct {
	// 渠道推荐数据
	List []QueryRecommendData `json:"list"`

	// MetaData describes the MetaData
	Meta MetaData `json:"meta"`
}

// QueryRecommendRsp defines model for QueryRecommendRsp.
type QueryRecommendRsp struct {
	// code
	Code int64               `json:"code"`
	Data *QueryRecommendInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UpdateAttributeData defines model for UpdateAttributeData.
type UpdateAttributeData struct {
	// list
	List *[]UpdateAttributeInfo `json:"list,omitempty"`
}

// UpdateAttributeInfo defines model for UpdateAttributeInfo.
type UpdateAttributeInfo struct {
	// 渠道ID
	ChannelId *int64 `json:"channel_id,omitempty"`

	// 失败原因
	Reason *string `json:"reason,omitempty"`

	// 状态（0 创建成功 1 创建失败）
	Status *int32 `json:"status,omitempty"`
}

// UpdateAttributeRsp defines model for UpdateAttributeRsp.
type UpdateAttributeRsp struct {
	// code
	Code int                  `json:"code"`
	Data *UpdateAttributeData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UpdateChannelCostBatchInfo defines model for UpdateChannelCostBatchInfo.
type UpdateChannelCostBatchInfo struct {
	// 状态
	Status int `json:"status"`
}

// UpdateChannelCostBatchRsp defines model for UpdateChannelCostBatchRsp.
type UpdateChannelCostBatchRsp struct {
	// code
	Code int64                       `json:"code"`
	Data *UpdateChannelCostBatchInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UpdateChannelCostStatusRequestBody defines model for UpdateChannelCostStatusRequestBody.
type UpdateChannelCostStatusRequestBody struct {
	// 排除国际二字码
	CountryCodes []string `json:"country_codes"`

	// 渠道ID
	Ids []int64 `json:"ids"`

	// 状态（0 不启用 1 启用）
	Status UpdateChannelCostStatusRequestBodyStatus `json:"status"`
}

// 状态（0 不启用 1 启用）
type UpdateChannelCostStatusRequestBodyStatus bool

// UpdateChannelCostStatusRsp defines model for UpdateChannelCostStatusRsp.
type UpdateChannelCostStatusRsp struct {
	// code
	Code int64                     `json:"code"`
	Data *UpdateCustomerConfigData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UpdateChannelInfo defines model for UpdateChannelInfo.
type UpdateChannelInfo struct {
	// 渠道ID
	Status int `json:"status"`
}

// UpdateChannelRsp defines model for UpdateChannelRsp.
type UpdateChannelRsp struct {
	// code
	Code int64              `json:"code"`
	Data *UpdateChannelInfo `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UpdateCustomerConfigData defines model for UpdateCustomerConfigData.
type UpdateCustomerConfigData struct {
	// 状态（0 更新成功 1 更新失败）
	Status int8 `json:"status"`
}

// UpdateCustomerConfigRequestBody defines model for UpdateCustomerConfigRequestBody.
type UpdateCustomerConfigRequestBody struct {
	// 排除国际二字码
	CountryCodes []string `json:"country_codes"`

	// 渠道ID
	Ids []int64 `json:"ids"`

	// 状态（0 创建成功 1 创建失败）
	Status UpdateCustomerConfigRequestBodyStatus `json:"status"`
}

// 状态（0 创建成功 1 创建失败）
type UpdateCustomerConfigRequestBodyStatus bool

// UpdateRecommendRequestBody defines model for UpdateRecommendRequestBody.
type UpdateRecommendRequestBody struct {
	// 国际二字码
	CountryCode string `json:"country_code"`

	// 是否推荐
	IsRecommended UpdateRecommendRequestBodyIsRecommended `json:"is_recommended"`

	// 是否可用
	Status UpdateRecommendRequestBodyStatus `json:"status"`
}

// 是否推荐
type UpdateRecommendRequestBodyIsRecommended bool

// 是否可用
type UpdateRecommendRequestBodyStatus bool

// UpdateRequestBody defines model for UpdateRequestBody.
type UpdateRequestBody struct {
	// 渠道类型（1 快递, 2 专线， 3邮政）
	ChannelType int8 `json:"channel_type"`

	// API服务代码
	Code string `json:"code"`

	// 渠道平台
	CourierPlatform string `json:"courier_platform"`

	// 渠道类型（ddu, ddp）
	DeliverDuty string `json:"deliver_duty"`

	// 渠道对外展示名称
	DisplayName string `json:"display_name"`

	// 渠道英文名称
	EnName string `json:"en_name"`

	// 排除属性
	ExcludeAttributes []string `json:"exclude_attributes"`

	// 最大边长
	MaxLength *int `json:"max_length,omitempty"`

	// 最大三边之和(长+宽+高)
	MaxThreeSideSum *int `json:"max_three_side_sum,omitempty"`

	// 最小边长
	MinLength *int `json:"min_length,omitempty"`

	// 渠道中文名称
	Name string `json:"name"`

	// 是否启动预付关税
	PrepayTariff UpdateRequestBodyPrepayTariff `json:"prepay_tariff"`

	// 流水线出口
	SortingPort int `json:"sorting_port"`

	// 是否特殊渠道（0 正常 1 特别）
	Special int8 `json:"special"`

	// 渠道可用状态
	Status int `json:"status"`

	// 是否是测试渠道
	Test UpdateRequestBodyTest `json:"test"`

	// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
	Type UpdateRequestBodyType `json:"type"`

	// 是否虚拟渠道（0 虚拟 1 真实）
	Virtual int8 `json:"virtual"`

	// 计泡系数
	VolumeFactor *int `json:"volume_factor,omitempty"`
}

// 是否启动预付关税
type UpdateRequestBodyPrepayTariff bool

// 是否是测试渠道
type UpdateRequestBodyTest bool

// 渠道类型（1 Economic 经济 2 Fast 快速 3 Recommend 推荐）
type UpdateRequestBodyType int

// UploadChannelCostData defines model for UploadChannelCostData.
type UploadChannelCostData struct {
	// status
	Status int32 `json:"status"`
}

// UploadChannelCostRsp defines model for UploadChannelCostRsp.
type UploadChannelCostRsp struct {
	// code
	Code int64                  `json:"code"`
	Data *UploadChannelCostData `json:"data,omitempty"`

	// message
	Message string `json:"message"`
}

// UploadRequestBody defines model for UploadRequestBody.
type UploadRequestBody struct {
	// file
	File string `json:"file"`

	// file name
	FileName string `json:"file_name"`
}

// GetParams defines parameters for Get.
type GetParams struct {
	// 渠道平台
	ChannelPlatform *string `json:"channel_platform,omitempty"`

	// 渠道代码
	ChannelCode *string `json:"channel_code,omitempty"`

	// 渠道中文名称
	ChannelName *string `json:"channel_name,omitempty"`

	// 基于此排序查询字段（desc 降序 asc 升序）
	Sorter *string `json:"sorter,omitempty"`

	// current
	Current *int `json:"current,omitempty"`

	// page_size
	PageSize *int `json:"page_size,omitempty"`
}

// PostJSONBody defines parameters for Post.
type PostJSONBody CreateRequestBody

// PostAttributesJSONBody defines parameters for PostAttributes.
type PostAttributesJSONBody CreateAttributeRequestBody

// PutAttributesJSONBody defines parameters for PutAttributes.
type PutAttributesJSONBody BatchUpdateRequestBody

// PutCostsJSONBody defines parameters for PutCosts.
type PutCostsJSONBody UpdateChannelCostStatusRequestBody

// GetCustomerConfigsParams defines parameters for GetCustomerConfigs.
type GetCustomerConfigsParams struct {
	// 渠道ID
	ChannelId *int64 `json:"channel_id,omitempty"`

	// 排序（asc desc）
	Sorter *string `json:"sorter,omitempty"`

	// 是否可用
	Status *GetCustomerConfigsParamsStatus `json:"status,omitempty"`

	// current
	Current *int `json:"current,omitempty"`

	// page_size
	PageSize *int `json:"page_size,omitempty"`
}

// GetCustomerConfigsParamsStatus defines parameters for GetCustomerConfigs.
type GetCustomerConfigsParamsStatus bool

// PostCustomerConfigsJSONBody defines parameters for PostCustomerConfigs.
type PostCustomerConfigsJSONBody CreateCustomerConfigRequestBody

// PutCustomerConfigsJSONBody defines parameters for PutCustomerConfigs.
type PutCustomerConfigsJSONBody UpdateCustomerConfigRequestBody

// GetRecommendsParams defines parameters for GetRecommends.
type GetRecommendsParams struct {
	// 国际二字码
	CountryCode *string `json:"country_code,omitempty"`

	// 渠道ID
	ChannelId *int64 `json:"channel_id,omitempty"`

	// 是否推荐
	IsRecommended *GetRecommendsParamsIsRecommended `json:"is_recommended,omitempty"`

	// 是否可用
	Status *GetRecommendsParamsStatus `json:"status,omitempty"`

	// current
	Current *int `json:"current,omitempty"`

	// page_size
	PageSize *int `json:"page_size,omitempty"`

	// 排序（asc desc）
	Sorter *string `json:"sorter,omitempty"`
}

// GetRecommendsParamsIsRecommended defines parameters for GetRecommends.
type GetRecommendsParamsIsRecommended bool

// GetRecommendsParamsStatus defines parameters for GetRecommends.
type GetRecommendsParamsStatus bool

// GetChannelIdCostBatchesParams defines parameters for GetChannelIdCostBatches.
type GetChannelIdCostBatchesParams struct {
	// 渠道批次ID
	Id *int `json:"id,omitempty"`

	// 生效日期
	EffectiveDate *string `json:"effective_date,omitempty"`

	// 状态
	Status *int `json:"status,omitempty"`

	// 基于此排序查询字段（desc 降序 asc 升序）
	Sorter *string `json:"sorter,omitempty"`

	// current
	Current *int `json:"current,omitempty"`

	// page_size
	PageSize *int `json:"page_size,omitempty"`
}

// PostChannelIdCostBatchesJSONBody defines parameters for PostChannelIdCostBatches.
type PostChannelIdCostBatchesJSONBody CreateChannelCostBatchRequestBody

// PutChannelIdCostBatchesIdJSONBody defines parameters for PutChannelIdCostBatchesId.
type PutChannelIdCostBatchesIdJSONBody CreateChannelCostBatchRequestBody

// GetChannelIdCostsChannelCostBatchIdParams defines parameters for GetChannelIdCostsChannelCostBatchId.
type GetChannelIdCostsChannelCostBatchIdParams struct {
	// 国家代码
	CountryCode *string `json:"country_code,omitempty"`

	// 基于此排序查询字段（desc 降序 asc 升序）
	Sorter *string `json:"sorter,omitempty"`

	// current
	Current *int `json:"current,omitempty"`

	// page_size
	PageSize *int `json:"page_size,omitempty"`

	// 状态（0 不启用 1 启用）
	Status *int8 `json:"status,omitempty"`
}

// PutIdJSONBody defines parameters for PutId.
type PutIdJSONBody UpdateRequestBody

// PostIdRecommendsJSONBody defines parameters for PostIdRecommends.
type PostIdRecommendsJSONBody CreateRecommendRequestBody

// PutIdRecommendsJSONBody defines parameters for PutIdRecommends.
type PutIdRecommendsJSONBody UpdateRecommendRequestBody

// PostJSONRequestBody defines body for Post for application/json ContentType.
type PostJSONRequestBody PostJSONBody

// PostAttributesJSONRequestBody defines body for PostAttributes for application/json ContentType.
type PostAttributesJSONRequestBody PostAttributesJSONBody

// PutAttributesJSONRequestBody defines body for PutAttributes for application/json ContentType.
type PutAttributesJSONRequestBody PutAttributesJSONBody

// PutCostsJSONRequestBody defines body for PutCosts for application/json ContentType.
type PutCostsJSONRequestBody PutCostsJSONBody

// PostCustomerConfigsJSONRequestBody defines body for PostCustomerConfigs for application/json ContentType.
type PostCustomerConfigsJSONRequestBody PostCustomerConfigsJSONBody

// PutCustomerConfigsJSONRequestBody defines body for PutCustomerConfigs for application/json ContentType.
type PutCustomerConfigsJSONRequestBody PutCustomerConfigsJSONBody

// PostChannelIdCostBatchesJSONRequestBody defines body for PostChannelIdCostBatches for application/json ContentType.
type PostChannelIdCostBatchesJSONRequestBody PostChannelIdCostBatchesJSONBody

// PutChannelIdCostBatchesIdJSONRequestBody defines body for PutChannelIdCostBatchesId for application/json ContentType.
type PutChannelIdCostBatchesIdJSONRequestBody PutChannelIdCostBatchesIdJSONBody

// PutIdJSONRequestBody defines body for PutId for application/json ContentType.
type PutIdJSONRequestBody PutIdJSONBody

// PostIdRecommendsJSONRequestBody defines body for PostIdRecommends for application/json ContentType.
type PostIdRecommendsJSONRequestBody PostIdRecommendsJSONBody

// PutIdRecommendsJSONRequestBody defines body for PutIdRecommends for application/json ContentType.
type PutIdRecommendsJSONRequestBody PutIdRecommendsJSONBody
