name: reviewdog
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.19"
          golangci_lint_flags: "--config=.golangci.yml"
