run:
  timeout: 30m

issues:
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # exclude ineffable linter for generated files for conversion
    - path: conversion\.go
      linters:
        - ineffassign

linters:
  disable:
    - exhaustivestruct #这个规则是让把定义的结构体中的每个值都赋值，通常大多都是只给想要的值.
    - ireturn  #return interface 研究了官方文档，没有实用性(可以选择不同的设计模式去检验)
    - scopelint #deprecated 已经弃用,不想看到警告提示
    - interfacer #deprecated  已经弃用,不想看到警告提示
    - maligned #deprecated  已经弃用,不想看到警告提示
    - golint #deprecated  已经弃用,不想看到警告提示
    - gochecknoglobals
    - bodyclose #disabled because of go1.18.
    - contextcheck #disabled because of go1.18.
    - gosimple #disabled because of go1.18.
    - nilerr #disabled because of go1.18.
    - noctx #disabled because of go1.18.
    - rowserrcheck #disabled because of go1.18.
    - sqlclosecheck #disabled because of go1.18.
    - staticcheck #disabled because of go1.18.
    - structcheck #disabled because of go1.18.
    - stylecheck #disabled because of go1.18.
    - tparallel #disabled because of go1.18.
    - unparam #disabled because of go1.18.
    - wastedassign #disabled because of go1.18.
    - unused #disabled because of go1.18.
    - tagliatelle
    - exhaustruct
    - nonamedreturns
  enable-all: true

linters-settings: # please keep this alphabetized
  cyclop:
    max-complexity: 50
  funlen:
    lines: 160
    statements: 100
  gocognit:
    min-complexity: 85
  staticcheck:
    go: "1.18"
    checks: [
        "all",
        "-S1*",    # TODO(fix) Omit code simplifications for now.
        "-ST1*",   # Mostly stylistic, redundant w/ golint
        "-SA5011", # TODO(fix) Possible nil pointer dereference
        "-SA1019", # TODO(fix) Using a deprecated function, variable, constant or field
        "-SA2002"  # TODO(fix) Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
    ]
  varnamelen:
    ignore-names:
      - "w"
      - "r"
      - "i"
      - "id"
      - "tx"
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
         - argument
         - case
         - condition
         - return
        ignored-numbers: 0,1,2,3
        ignored-functions: strings.SplitN
  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 4

  unused:
    go: "1.18"
